spring.application.name=marketplace

#config database
###
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate/JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' automatically updates your DB schema based on your Java Entity classes. Use 'validate' in production.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
